name: umsukoas
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  lottie: ^1.2.1
  intl: ^0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  material_design_icons_flutter: ^5.0.6595
  flutter_login: ^3.1.0
  carousel_slider: ^4.0.0
  pull_to_refresh: ^2.0.0
  sweetalert: ^0.0.1
  flutter_progress_hud: ^2.0.0
  shared_preferences:
  syncfusion_flutter_calendar: ^19.4.40
  zefyrka: ^1.1.1
  notus_to_html_to_notus: ^0.0.2
  flutter_quill: ^3.0.4
  tuple: ^2.0.0
  file_picker: ^4.3.0
  path_provider: ^2.0.8
  filesystem_picker: ^2.0.0
  path: ^1.8.0
  universal_html: ^2.0.8
  geolocator: ^8.0.1
  geocoding: ^2.0.1
  syncfusion_flutter_pdfviewer: ^19.4.41-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.3.2

flutter_native_splash:
  color: "#ffffff"
  image: "asset/images/logoumsu.png"
  color_dark: "#1a1a1a"
  image_dark: "asset/images/logoumsu.png"
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/launchers/drmuda.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/
    - asset/icons/
    - asset/lotties/
    - asset/launchers/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
